import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { ErrorBoundary } from 'next/dist/client/components/error-boundary'
import ErrorHandler from '@/components/error/errorHandler';
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className="relative  ">
                <div className="h-16 w-screen bg-white anchor-scroll"></div>

                <div className="md:w-34 bg-white w-screen lg:w-10/12 xl:w-8/12 mx-auto mt-10 mb-7 rounded-lg p-3 ">
                    <ErrorBoundary errorComponent={ErrorHandler}>
                        {children}
                    </ErrorBoundary>
                </div>
            </body>
        </html>
    )
}
