import '../globals.css'
import "@fortawesome/fontawesome-svg-core/styles.css";

import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ErrorBoundary } from 'next/dist/client/components/error-boundary'
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';

import Navigation from '@/components/navigation/navigation';
import ErrorHandler from '@/components/error/errorHandler';

// Font awesome
import { config } from "@fortawesome/fontawesome-svg-core";
import BackgroundLayout from '@/components/layouts/background/background';
import Footer from '@/components/footer/footer';
import Providers from './providers';
config.autoAddCss = false;

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export function generateStaticParams() {
    return [{ locale: 'en' }, { locale: 'bg' }];
}

export default async function RootLayout({
    children,
    params: { locale }
}: {
    children: React.ReactNode,
    params: { locale: any }
}) {
    let messages;

    try {
        messages = (await import(`../../messages/${locale}.json`)).default;
    } catch (error) {
        notFound();
    }

    return (
        <html lang="en">
            <body className="relative gradient-bg">
                <Providers>
                    <NextIntlClientProvider locale={locale} messages={messages}>
                        <Navigation />

                        <ErrorBoundary errorComponent={ErrorHandler}>
                            {children}
                        </ErrorBoundary>

                        <Footer></Footer>

                        <BackgroundLayout></BackgroundLayout>
                    </NextIntlClientProvider>
                </Providers>
            </body>
        </html>
    )
}
